<button type="button" class="btn btn-default btn-lg btn-block">Guest</button>
<button type="button" class="btn btn-success btn-lg btn-block">Member</button>
<button type="button" class="btn btn-primary btn-lg btn-block">Regsiter</button>

=======Colors=======
navbar background: #F8F8F8; , #293E6A
navbar border
default color
hover color (#5E5E5E for .nav-brand)
active color
active background


/* As hex codes */

.color-primary-0 { color: #343477 }	/* Main Primary color */
.color-primary-1 { color: #7373B3 }
.color-primary-2 { color: #505095 }
.color-primary-3 { color: #1D1D59 }
.color-primary-4 { color: #0D0D3B }

/* Generated by Paletton.com Â© 2002-2014 */
/* http://paletton.com */

#293E6A, 3B5998, 639BF1

0F0B42, 231E60, 3D387C, 5F5B9A, 8A87B8

#8184B, #565B95, #343977, #1A1F5A, #090D3C